name: WeaveCustomSchedule
version: '${version}'
main: cn.yxgeneral.weavestudio.weavecustomschedule.WeaveCustomSchedule
api-version: '1.20'

softdepend:
  - PlaceholderAPI

commands:
    weavecustomschedule:
        description: "weavecustomschedule root command"
        usage: /weavecustomschedule
        aliases: [weavecustomschedule, wcs]
